[package]
name = "sanskriti"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
bytes = "1.3.0"
clap = { version = "4.5.16", features = ["derive"] }
thiserror = "1.0.63"
